#!/usr/bin/env bash
# Bash script that transfers a file from a client to a server
if [ $# -lt 5]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i ~/.ssh/school -r -v "$1" "$2"@"$3":"$4"
fi
