#!/usr/bin/env bash
# print Best School 10 times using while loop but for the 9th iteration, displays Best School and then Hi
count=1
while [ $count -le 10 ]
do
    echo "Best School"
    if [ $count -eq 9 ]
    then
        echo "Hi"
    fi
    ((count++))
done
