#!/usr/bin/env bash
# bash scripts that prints Hello School 8 times and a diffrenct text on the 8th and 4th iteration

i=1
while [ $i -lt 11 ];
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
