#!/usr/bin/env bash
# print numbers 1 to 20 using while loop but for 4th, 8th , 17thiterations print something else too
count=1
while [ $count -le 20 ]
do
    echo "$count"
    if [ $count -eq 4 ]
    then
        echo "bad luck from China"
    elif [ $count -eq 8 ]
    then
        echo "bad luck from Japan"
    elif [ $count -eq 17 ]
    then
        echo "bad luck from Japan"
    fi
    ((count++))
done
