#!/usr/bin/env bash
# print numbers 1 to 20 using while loop but for 4th, 8th , 17thiterations print something else too
count=1
while [ $count -le 20 ]
do
    echo "$count"
    case $count in
    4)
        echo "bad luck from China"
        ;;
    8)
        echo "bad luck from Japan"
        ;;
    17)
        echo "bad luck from Japan"
        ;;
    esac
    ((count++))
done
