#!/usr/bin/env bash
#script to list files in current directory

list="$(ls)"

for file in $list
do
    if [[ $file != .* ]]
    then
        tmp=$(echo "$file" | cut -d'-' -f2-)
        echo "$tmp"
    fi
done
